type Item={id:string;label:string;aliases:string[]};
type Catalog={cpus:Item[];gpus:Item[]};
type Hit={item:Item;score:number;alias:string|null};
const MAX=8;
let serial=0;
const norm=(s:string)=>s.normalize("NFKC").toLowerCase().replace(/[®™]/g,"").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();
const compact=(s:string)=>norm(s).replace(/\s/g,"");
function textScore(query:string,value:string):number|null{const q=norm(query),v=norm(value);if(!q||!v)return null;if(v===q)return 0;if(v.startsWith(q))return 10+Math.min(8,v.length-q.length);const cq=compact(q),cv=compact(v);if(cv===cq)return 20;if(cv.startsWith(cq))return 30+Math.min(10,cv.length-cq.length);if(v.includes(q))return 50+v.indexOf(q);if(cv.includes(cq))return 65+cv.indexOf(cq);const qt=q.split(" "),vt=v.split(" ");return qt.length>1&&qt.every(t=>vt.some(p=>p.startsWith(t)))?80+vt.length-qt.length:null;}
function rank(items:Item[],query:string):Hit[]{if(!query.trim())return[];const hits:Hit[]=[];for(const item of items){let best:number|null=textScore(query,item.label),alias:string|null=null;for(const a of item.aliases??[]){const s=textScore(query,a);if(s!==null&&(best===null||s+2<best)){best=s+2;alias=a;}}if(best!==null)hits.push({item,score:best,alias});}return hits.sort((a,b)=>a.score-b.score||a.item.label.length-b.item.label.length||a.item.label.localeCompare(b.item.label)).slice(0,MAX);}
function setValue(input:HTMLInputElement,value:string){const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set;if(setter)setter.call(input,value);else input.value=value;input.dispatchEvent(new Event("input",{bubbles:true}));}
function enhance(input:HTMLInputElement,items:Item[]){if(input.dataset.catalogSuggest)return;input.dataset.catalogSuggest="1";const host=input.parentElement;if(!host)return;host.classList.add("catalog-suggest-field");const list=input.getAttribute("list");if(list)input.dataset.catalogNativeList=list;input.removeAttribute("list");input.autocomplete="off";input.setAttribute("role","combobox");input.setAttribute("aria-autocomplete","list");input.setAttribute("aria-expanded","false");const menu=document.createElement("div"),id=`catalog-suggest-${++serial}`;menu.id=id;menu.className="catalog-suggest-menu";menu.setAttribute("role","listbox");menu.hidden=true;host.append(menu);input.setAttribute("aria-controls",id);let hits:Hit[]=[],active=-1;const close=()=>{menu.hidden=true;active=-1;input.setAttribute("aria-expanded","false");input.removeAttribute("aria-activedescendant");};const choose=(i:number)=>{if(!hits[i])return;setValue(input,hits[i].item.label);close();input.focus();};const activate=(i:number)=>{if(!hits.length)return;active=(i+hits.length)%hits.length;menu.querySelectorAll<HTMLElement>("[role=option]").forEach((el,n)=>{const on=n===active;el.classList.toggle("active",on);el.setAttribute("aria-selected",on?"true":"false");if(on){input.setAttribute("aria-activedescendant",el.id);el.scrollIntoView({block:"nearest"});}});};const render=()=>{hits=rank(items,input.value);menu.replaceChildren();active=-1;if(!hits.length){close();return;}hits.forEach((hit,i)=>{const option=document.createElement("button");option.type="button";option.className="catalog-suggest-option";option.id=`${id}-${i}`;option.setAttribute("role","option");option.setAttribute("aria-selected","false");const strong=document.createElement("span");strong.className="catalog-suggest-label";strong.textContent=hit.item.label;option.append(strong);if(hit.alias&&norm(hit.alias)!==norm(hit.item.label)){const small=document.createElement("small");small.textContent=`一致: ${hit.alias}`;option.append(small);}option.addEventListener("pointerdown",e=>{e.preventDefault();choose(i);});menu.append(option);});menu.hidden=false;input.setAttribute("aria-expanded","true");};input.addEventListener("input",render);input.addEventListener("focus",render);input.addEventListener("blur",()=>setTimeout(close,120));input.addEventListener("keydown",e=>{if(e.key==="ArrowDown"){if(menu.hidden)render();if(hits.length){e.preventDefault();activate(active+1);}}else if(e.key==="ArrowUp"){if(menu.hidden)render();if(hits.length){e.preventDefault();activate(active<=0?hits.length-1:active-1);}}else if(e.key==="Enter"&&active>=0){e.preventDefault();choose(active);}else if(e.key==="Escape")close();});}
function attach(catalog:Catalog){const apply=()=>{document.querySelectorAll<HTMLInputElement>('input[list="cpu-list"],input[data-catalog-native-list="cpu-list"]').forEach(i=>enhance(i,catalog.cpus));document.querySelectorAll<HTMLInputElement>('input[list="gpu-list"],input[data-catalog-native-list="gpu-list"]').forEach(i=>enhance(i,catalog.gpus));};apply();new MutationObserver(apply).observe(document.body,{childList:true,subtree:true});}
export async function installCatalogSuggest(){try{const response=await fetch("/api/v1/catalog",{headers:{accept:"application/json"}});if(!response.ok)return;const catalog=await response.json() as Catalog;if(Array.isArray(catalog.cpus)&&Array.isArray(catalog.gpus))attach(catalog);}catch{/* native datalist stays usable */}}
